spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql_test
    username: root
    password: 123456

  application:
    name: complex-seed

nazzd:
  seed:
    web:
      response-body-advice: false


server:
  port: 8099
  servlet:
    context-path: /complex

unit:
  base:
    10001:
      id: 10001
      poolSize: 3
      queueSize: 20
      timeOuts: 2000
    10002:
      id: 10001
      poolSize: 3
      queueSize: 20
      timeOuts: 2000
